### ISSUE TITLE
Update documentation URLs in DevTools

### ISSUE THREAD

**Issue by Mamaduka** [replayio/docs#53]
I noticed that some of the documentation links point to 404 pages. I assume this is due to a recent restructuring of the site (which looks great, by the way).

A few examples:

* https://github.com/replayio/devtools/blob/1f749cda31609782bfdf1182b2b5717ef7ad0b37/src/ui/components/Timeline/FocusModePopout.tsx#L139
* https://github.com/replayio/devtools/blob/1f749cda31609782bfdf1182b2b5717ef7ad0b37/src/ui/components/SidePanel.tsx#L152

**Comment by jasonLaster** [comment]
Thanks @Mamaduka
